### PR TITLE
Remove VectorLayout from Flatbuffers, Java implementation

### PR DESCRIPTION
**Pull request by icexelloss**

### CODE REVIEW

**Comment by icexelloss** [comment]
@wesm can you rebase your branch on master? Integration test is passing.

**Comment by wesm** [comment]
Done, sweet, I will review!

**Comment by wesm** [comment]
The Java build failed

**Comment by icexelloss** [comment]
oops, I missed one commit for some reason.

**Comment by icexelloss** [comment]
A fat finger.

**Comment by wesm** [comment]
Pulling these changes into my branch

**Pull request closed without merging**
