### PR TITLE
simple roundtrip

### PR DESCRIPTION
**Pull request by julienledem**
Still TODO: actually read the values from a vector and write them back to a new one.
This one just reads the buffers in a vector and writes them back.

### CODE REVIEW

**Comment by wesm** [comment]
How do I run this program? I don't know how to set the right classpath

**Comment by julienledem** [comment]
to try it out:

```
mvn package
java -cp tools/target/arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar org.apache.arrow.tools.FileRoundtrip -in foo -out bar
```

**Comment by wesm** [comment]
Thank you! I will start with this and work on an initial "hello world" integration test

**Comment by wesm** [comment]
Merged these commits into my branch. Very helpful, thank you

**Pull request merged**
