### PR TITLE
Update clang

### PR DESCRIPTION
**Pull request by xhochy**
Locally this is the only thing that needs to be changed to get LLVM 7 to work on manylinux1

### CODE REVIEW

**Comment by wesm** [comment]
Hm I wonder why my local docker build failed?

**Comment by xhochy** [comment]
> Hm I wonder why my local docker build failed?

The default docker command in the README uses the image from `quay.io` and not the local build. Maybe a c&p mistake?

**Comment by wesm** [comment]
No the base image build failed

**Comment by xhochy** [comment]
I tested locally only for Python 2 which does not support Gandiva 🤦‍♂️

**Comment by xhochy** [comment]
@wesm at least you should be able to merge these commits and continue with this in your PR

**Comment by xhochy** [comment]
> No the base image build failed

Maybe execute `docker pull quay.io/pypa/manylinux1_x86_64:latest` to have the latest base image. This was is not pulled automatically on updates.

**Comment by wesm** [comment]
I see, it may be because my manylinux1 base image is stale. I'll try that

**Comment by wesm** [comment]
Cherry-picked these commits

**Pull request closed without merging**
